#include<stdio.h>
void hailstone(int m)
{
    printf("input a number:Hailstone generated by %d:\n",m);
    int n[10000];
    n[0]=m;
    int count=1;
    for(int i=0;;i++)
    {
        if(n[i]%2==0)
        {
            n[i+1]=n[i]/2;
        }else{
            n[i+1]=3*n[i]+1;
        }
        count++;
        if((i+1)%6==0&&i!=0){
            printf("%5d\n",n[i+1]);
        }else
        {
            printf("%5d",n[i+1]);
        }
        if(n[i+1]==1)
        {
        printf("\n");
        break;
        }
    }
    printf("Number of hailstone generated:%d",count);
}
int main()
{
    int n;
    scanf("%d",&n);
    hailstone(n);
    return 0;
}
//要软硬通吃
//工程 1复杂性 2学会借鉴 不要重复造两个一样的轮胎